services:
  mongo:
    image: mongo:latest
    container_name: tcc-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tcc
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
